---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-identityserver
  labels:
    app: demo-identityserver
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: demo-identityserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: demo-identityserver
    spec:
      containers:
      - name: demo-identityserver
        image: fnandop/demo-identityserver:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: demo-identityserver-env
      terminationGracePeriodSeconds: 180