parameters:
  orders_api:
    port_http: "8080"
    port_https: "8343"
    orders_api_image: "orders-api:latest"
  customers_api:
    port_http: "8080"
    port_https: "8343"
    customers_api_image: "customers-api:latest"
  demo_identityserver:
    port_http: "8080"
    port_https: "8343"
    demo_identityserver_image: "demo-identityserver:latest"
  reverse_proxy:
    port_http: "8080"
    port_https: "8343"
    reverse_proxy_image: "reverse-proxy:latest"
secrets: {}
config:
  orders_api:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  customers_api:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  demo_identityserver:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  reverse_proxy:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
