@baseUrl = https://localhost:7150
@authBaseUrl = https://localhost:7244


@client_id = protected-api-client-2
@client_secret = secret
@scope = protected-api
@access_token =eyJhbGciOiJSUzI1NiIsImtpZCI6IjEzNDI5NjI2MUMzQkJCMjJGNEZFOEY4NjUyODZENDkyIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MjQ0IiwibmJmIjoxNzcyMzk2MTAyLCJpYXQiOjE3NzIzOTYxMDIsImV4cCI6MjA4Nzc1NjEwMiwic2NvcGUiOlsiY3VzdG9tZXJzLnJlYWQiLCJjdXN0b21lcnMud3JpdGUiLCJvcmRlcnMucmVhZCIsIm9yZGVycy53cml0ZSJdLCJjbGllbnRfaWQiOiJwcm90ZWN0ZWQtYXBpLWNsaWVudC0yIiwiY2xpZW50X3RlbmFudElkIjoidGVuYW50LTIiLCJqdGkiOiI4MzI1MkUzNEU4Mjc5NkIzOUI4RTc2MDQ3NDAyNEI4NSJ9.nbExOP2bzTnOaJa9tQ4ucG5JYyyl8WHM1v8DLjnAG_VyZEqXRYefRk1XWPUo1l2Fzn53xhj1249hGiSsMa1wZrjvczL9Kk-Y23SA-EddYkTK6QKlI6r1XuU_f866BFhDZntNjflOdp4697Py0zDMoqFrDzGzA-zyM17LkjP_fzGjsJshdhCtWndhZjyu5PaikU1Mf6W9StRi21qT9jJENjoTJ0lwE1LS97scqWKTXDtVYgyHCjPiqPIlOXcFuqReQi_eIZchswu5bQm-BKw545-sPOFg2k-jxb7n9FAwvzBxikbGXX1GRAPcwhp4orDZCkID0CaIgwTwrwv2AQW-9w


### 1) Get access token (client_credentials) and copy the access_token from the response (or use the saved variable)
POST {{authBaseUrl}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{client_id}}&client_secret={{client_secret}}



### GET Orders from Gateway Auth Demo expected Status: 200 OK
GET {{baseUrl}}/auth-demo/orders
Authorization: Bearer {{access_token}}

### Post Order to Gateway Auth Demo
Post {{baseUrl}}/auth-demo/orders
Authorization: Bearer {{access_token}}
{
    "prop1": "value1"
}

### Get Order with id 1 from Gateway Auth Demo
GET {{baseUrl}}/auth-demo/orders/1
Authorization: Bearer {{access_token}}

### Put Order to Gateway Auth Demo Status: 200 OK
Put {{baseUrl}}/auth-demo/orders/1
Authorization: Bearer {{access_token}}
{
    "prop1": "value1"
}

### GET customers from Gateway Auth Demo Status: 200 OK
GET {{baseUrl}}/auth-demo/customers
Authorization: Bearer {{access_token}}

### Get Order with id 1 from Gateway Auth Demo Status: 200 OK
GET {{baseUrl}}/auth-demo/customers/1
Authorization: Bearer {{access_token}}


### Post Order to Gateway Auth Demo Status: 200 OK
Post {{baseUrl}}/auth-demo/customers
Authorization: Bearer {{access_token}}
{
    "prop1": "value1"
}

### Put Order to Gateway Auth Demo Status: 200 OK
Put {{baseUrl}}/auth-demo/customers/1
Authorization: Bearer {{access_token}}
{
    "prop1": "value1"
}

