@baseUrl = https://localhost:7150
@authBaseUrl = https://localhost:7244


@client_id = protected-api-client-2
@client_secret = secret

@access_token =eyJhbGciOiJSUzI1NiIsImtpZCI6IjEzNDI5NjI2MUMzQkJCMjJGNEZFOEY4NjUyODZENDkyIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MjQ0IiwibmJmIjoxNzcyMzAxMzM2LCJpYXQiOjE3NzIzMDEzMzYsImV4cCI6MjA4NzY2MTMzNiwic2NvcGUiOlsicHJvdGVjdGVkLWFwaSIsInByb3RlY3RlZC1hcGk6YmFuYW5hcyJdLCJjbGllbnRfaWQiOiJwcm90ZWN0ZWQtYXBpLWNsaWVudC0yIiwiY2xpZW50X3RlbmFudElkIjoidGVuYW50LTIiLCJqdGkiOiJCQTlFQjRDRDEzRDJCQUQ1MzkxNDA5MjIzNEI1MTMyRCJ9.PKbWHzpWWGoI_HTDinMZqXpLOFJdjL9u9AQb3lq5PCWdtOOJxIb5w4u5wyydurOtKlXy8PByfwDHkjROzMSR4SjPubIEKOOHvkTrY6c4XEOWStndV_eQ48nNd1gYYVg0hF3ohEK3UpiY9TahGNHbr_VhPToMzaeHdaFGWxhehzPjRCoKpFFuL8QzkxLKwTGCHK6vxp1J056snUUFfdcWD0y5KOE6i_r0fxBhuQPTJc04hQFsxz5JuQZP4tiFDe_oFAlQNR6Y9G7FhLcIRkYJIV0xRo1SoKqZ-GADsvhnKhqM8Kx0Ywbad7jJS0fGP6ZWtVy8qPJFt8M38H9GzEbf4w


### 1) Get access token (client_credentials) and copy the access_token from the response (or use the saved variable)
POST {{authBaseUrl}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{client_id}}&client_secret={{client_secret}}


### 2) Call Protected API unanuthenticated (no token, should fail) with Status: 401 Unauthorized
GET {{baseUrl}}/protected-api



### 3) Call Call Protected API route (uses the token) authenticated with Status: 200 OK
GET {{baseUrl}}/protected-api
Authorization: Bearer {{access_token}}


### 4) Call Call Protected API route (uses the token) authenticated with Status: Status: 200 OK
GET {{baseUrl}}/protected-api/potatos
Authorization: Bearer {{access_token}}




