---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  labels:
    app: reverse-proxy
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        image: fnandop/reverse-proxy:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: reverse-proxy-env
      terminationGracePeriodSeconds: 180