resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: reverse-proxy-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - HTTP_PORTS=8080
    - ORDERS_API_HTTP=http://orders-api:8080
    - services__orders-api__http__0=http://orders-api:8080
    - CUSTOMERS_API_HTTP=http://customers-api:8080
    - services__customers-api__http__0=http://customers-api:8080
    - DEMO_IDENTITYSERVER_HTTP=http://demo-identityserver:8080
    - services__demo-identityserver__http__0=http://demo-identityserver:8080
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=reverse-proxy
    - ASPNETCORE_URLS=http://+:8080;

