---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "demo-identityserver-service"
  labels:
    app.kubernetes.io/name: "yarpapigatewaydemos-apphost"
    app.kubernetes.io/component: "demo-identityserver"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "yarpapigatewaydemos-apphost"
    app.kubernetes.io/component: "demo-identityserver"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "http"
      protocol: "TCP"
      port: {{ .Values.parameters.demo_identityserver.port_http }}
      targetPort: {{ .Values.parameters.demo_identityserver.port_http }}
    - name: "https"
      protocol: "TCP"
      port: {{ .Values.parameters.demo_identityserver.port_https }}
      targetPort: {{ .Values.parameters.demo_identityserver.port_https }}
